DO $$
BEGIN
  CREATE TYPE "BomType" AS ENUM ('FG_BOM', 'FML_BOM');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE "BOM"
  ADD COLUMN IF NOT EXISTS "bomType" "BomType" NOT NULL DEFAULT 'FML_BOM',
  ADD COLUMN IF NOT EXISTS "parentItemId" TEXT;

ALTER TABLE "BOM"
  ADD CONSTRAINT "BOM_parentItemId_fkey"
  FOREIGN KEY ("parentItemId") REFERENCES "Item"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "BOMLine"
  ADD COLUMN IF NOT EXISTS "inputFormulaId" TEXT;

ALTER TABLE "BOMLine"
  ADD CONSTRAINT "BOMLine_inputFormulaId_fkey"
  FOREIGN KEY ("inputFormulaId") REFERENCES "Formula"("id") ON DELETE SET NULL ON UPDATE CASCADE;
